### PR TITLE
Become ramdisk independent

### PR DESCRIPTION
**Pull request by joe2k01**
Keeping compatibility with init scripts too

### CODE REVIEW

**Review by frap129 — CHANGES_REQUESTED** [review]
Please dont revert the empty case. Default case is correct format, even if its empty.

**Comment by frap129** [comment]
Also, I will make my own reference commits to link, since a dev may not necessarily want to modify interactive, and not all versions of interactive are directly compatible with the variable names you used. Otherwise, thanks for this!

**Comment by joe2k01** [comment]
The problem with the empty default  case is that it broke the build somehow, that's why I reverted it.
Anyway, codacy is complaining about the empty if case but I would left it there since KPM could conflict with the custom case

**Comment by joe2k01** [comment]
Applied the requested changes and fixed default case

**Comment by frap129** [comment]
@joe2k01 Don't want to do the same thing I did to harsh, merge now and we'll fix it up later.

**Pull request merged**
